# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# modified by rogermylife

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # __ORGID__
  # ---------------------------------------------------------------------------
  - Name: __ORGID__
    Domain: __ORGNAME__.chat-network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
