# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: chat-network.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: official
    Domain: official.chat-network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # scalable orgs will be appended as below
  # ---------------------------------------------------------------------------
