# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.2'

volumes:
  orderer.chat-network.com:
  peer0.official.chat-network.com:
__VOLUMES__

networks:
  chat-network:

services:

  orderer.chat-network.com:
    extends:
      file:   ../base/docker-compose-base.yaml
      service: orderer.chat-network.com
    container_name: orderer.chat-network.com
    networks:
      - chat-network

  peer0.official.chat-network.com:
    container_name: peer0.official.chat-network.com
    extends:
      file:  ../base/docker-compose-base.yaml
      service: peer0.official.chat-network.com
    networks:
      - chat-network

  ca.official.chat-network.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-official
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.official.chat-network.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/__CA_PRIVATE_KEY__
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/official.chat-network.com/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca.official.chat-network.com
    networks:
      - chat-network

  cli:
    container_name: cli
    image: rogermylife/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      # - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.official.chat-network.com:7051
      - CORE_PEER_LOCALMSPID=OfficialMSP
      - CORE_PEER_TLS_ENABLED=${TLS_ENABLED}
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/official.chat-network.com/peers/peer0.official.chat-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/official.chat-network.com/peers/peer0.official.chat-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/official.chat-network.com/peers/peer0.official.chat-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/official.chat-network.com/users/Admin@official.chat-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.chat-network.com
      - peer0.official.chat-network.com
    networks:
      - chat-network
__SERVICES__